### GIT HUB COMMANDS
* **git --version**
    * IT WILL PRINT VERSION OF OUR SYSTEM
* **git config user.name**
    * IT WILL PRINT THE USER NAME BUT IF ITS NOT UR SYSTEM IT WONT PRINT USERNAME TO GIVE UR USERNAME THE FOLLOWING COMMAND IS USED
* **git config --global user.name "ShaikShahitha"**
    * IT IS USED TO GET THE USER NAME
* **git config user.email**
    * IT IS USED TO PRINT THE EMAIL ID GIVEN IN GIT HUB ACCOUNT BUT HERE IT WONT PRINT.
* **git config --global user.email sheemasyed02@gmail.com**
    * IT IS USED TO ADD A MAIL
* **git status**
    * IT IS USED TO PRINT ALL THE FILES IN UR FOLDER.
* **git add .**
    * IT WILL ADD ALL THE FILES IN GIT BASH
* **git status**
    * IT WILL PRINT THE STATUS OF GIT BASH
* **git commit -m 'python content'**
    * IT IS A MESSAGE AFTER CHANGING THE FILE
* **git push nandini master**
    * IT IS USED TO PUSH ALL THE FILES IN THE GIT BASH.    

### NumPy

* Numerical python or numeric python
* NumPy supports a large number of mathematical operations
* NumPy is a programming language that deals with multi-demensional arrays and matrices

### WHY NumPy
* NumPy is memory efficiency,meaning itcan handle the vast amount of data more accessible than any other 
* especially for matrix multiplication and reshaping
* on top of that,NumPyis fast in fact,TensorFlow and Scikit

In [ ]:
### how to install
* NumPy

In [1]:
import numpy

In [2]:
import numpy as np


In [3]:
print(np.__version__)

1.19.2


In [ ]:
### Numpy Arrays

In [5]:
np.array([2,3,4,5])


array([2, 3, 4, 5])

In [7]:
print(np.array([2,3,4,5]))

[2 3 4 5]


In [9]:
data=np.array([[1,2,3,4],[5,6,7,8]])

In [10]:
data

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [12]:
print(data)

[[1 2 3 4]
 [5 6 7 8]]


In [14]:
a1=np.array([1,2,3,4])
a2=np.array([6,7,8,9])
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1%a2)


[ 7  9 11 13]
[-5 -5 -5 -5]
[ 6 14 24 36]
[1 2 3 4]


In [21]:
### shape of array
data=np.array([[1,2,3,4],[5,6,7,8]])
data1=np.array([[1.1,2.2,3.3,4.5],[5.0,6.0,7.0,8.0]])
print(np.shape(data))
print(data.dtype)
print(data1.dtype)


(2, 4)
int32
float64


In [23]:
data=np.array([[1,2,3,4],[5,6,7]])   # here two lists have different column sizes
print(np.shape(data))
print(data.dtype)

(2,)
object


<ipython-input-23-aaceb76ca9a1>:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray
  data=np.array([[1,2,3,4],[5,6,7]])


In [24]:
np.zeros((3,2),dtype=str)

array([['', ''],
       ['', ''],
       ['', '']], dtype='<U1')

In [25]:
np.zeros((3,2),dtype=int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [26]:
np.ones((3,2),dtype=str)

array([['1', '1'],
       ['1', '1'],
       ['1', '1']], dtype='<U1')

In [28]:
np.ones((3,2),dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [31]:
data=np.array([[1,2,3,4],[5,6,7,4]])
print(data)
data.reshape((4,2))

[[1 2 3 4]
 [5 6 7 4]]


array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 4]])

In [32]:
data.flatten() # convets any rows into a single row

array([1, 2, 3, 4, 5, 6, 7, 4])

In [34]:
print(data.flatten())

[1 2 3 4 5 6 7 4]


In [35]:
np.hstack((a1,a2))         # to print horizontally

array([1, 2, 3, 4, 6, 7, 8, 9])

In [36]:
np.vstack((a1,a2))            # to print vertically

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [37]:
np.vstack((a1))

array([[1],
       [2],
       [3],
       [4]])

In [38]:
print(data)
data.mean()

[[1 2 3 4]
 [5 6 7 4]]


4.0

In [39]:
print(data)
print(data.mean())
print(np.median(data))
print(np.mod(2,3))

[[1 2 3 4]
 [5 6 7 4]]
4.0
4.0
2


In [40]:
d=np.random.randint(1,30,(3,3))  # 1 to 30 random numbers in 3 rows and 3 columns

In [41]:
print(d)

[[ 9 27  9]
 [14 21  9]
 [27 18 15]]


In [43]:
d=np.random.randint(1,58,(5,7)) 
print(d)

[[ 5 18 57 51 15 46 51]
 [ 5 49  2 15 16  1 53]
 [19 35 26 32 29 49  2]
 [12 53 54  8 38 33 31]
 [40 26 19 55 27 14 31]]


In [46]:
np.random.normal(1,4,10)       #here 3rd arg is how many random nymbersb  here 1st arg is mean and 2nd is standard mean and 


array([-3.52574222, -1.87085446, 11.00275889,  5.28222413, -2.0792049 ,
        1.5020615 , -1.51085211, -1.52925911, -0.98653702,  3.27927413])

In [47]:
d.min()


-5.746740512386822

In [48]:
d.max()

5.740215062595321

In [49]:
data.std()

1.8708286933869707

In [53]:
print(data)
print(data.T)

[[1 2 3 4]
 [5 6 7 4]]
[[1 5]
 [2 6]
 [3 7]
 [4 4]]


In [54]:
np.eye(3)         # identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [55]:
print(a1)     
print(a2)
a1.dot(a2)

[1 2 3 4]
[6 7 8 9]


80

In [56]:
d1=np.array([1,2,3,4])
np.array([d1,pow(d1,3)])

array([[ 1,  2,  3,  4],
       [ 1,  8, 27, 64]])

In [61]:
a=np.repeat([1,2,3,4],3)
print(a)

[1 1 1 2 2 2 3 3 3 4 4 4]


In [62]:
a=np.array([1,2,3,4]*3)
print(a)

[1 2 3 4 1 2 3 4 1 2 3 4]


In [65]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [68]:
# syntax linspace(start,stop,num,endpoint)
np.linspace(1,5,num=10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [69]:
np.linspace(1,5)

array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ])

In [72]:
x=np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
print(x)
x[:,1]

[[1 2 3]
 [4 5 6]]


array([2, 5])

In [74]:
x[0]

array([1, 2, 3])

In [75]:
x[1:,2]

array([6])